[project]
name = "grax"
version = "0.1.0"
description = "GP regression using python and jax."
license = {file = "LICENSE"}
readme = "README.md"
authors = [{name = "Matthew W. Hoffman"}]
requires-python = ">=3.10"

dependencies = [
  "beartype",
  "jax",
  "jaxtyping",
  "optax",
]

[dependency-groups]
dev = [
  "ipython",
  "pytest",
  "pytest-cov",
  "ruff",
  "ty",
]
examples = [
  "matplotlib",
]

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.uv]
# Should match the version requirements of uv_build above.
required-version = ">=0.12,<0.13"

[tool.ruff]
indent-width = 2
line-length = 80
cache-dir = "~/.cache/ruff"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "PLC0105",  # Don't require suffixing typevar with their variance.
  "CPY001",   # Don't require copyright notices.
  "COM812",   # Don't require trailing commas.
  "F722",     # Ignore syntax errors in forward annotations which falsely flags
              # type strings in jaxtyping (see
              # https://docs.kidger.site/jaxtyping/faq/).
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
  "S101",          # Allow assertions.
  "PLR2004",       # Allow comparing against magic values.
  "SLF001",        # Allow private access in tests.
  "INP001",        # Treat tests/ as a flat directory, not a package.
  "D100", "D101",  # Don't require docstrings on tests.
  "D102", "D103",  # ...
]
"examples/**" = [
  "INP001",        # Treat examples/ as a flat directory, not a package.
]

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true

[tool.ruff.lint.isort]
force-single-line = true
lines-after-imports = 2

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
testpaths = ["tests"]
