name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked

      - name: Run linter
        run: uv run ruff check src tests

      - name: Run type checks
        run: uv run ty check src tests

      - name: Run tests
        run: uv run pytest tests

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --locked --group=examples

      - name: Run linter
        run: uv run ruff check examples

      - name: Run type checks
        run: uv run ty check examples

      - name: Cache example datasets
        uses: actions/cache@v6
        with:
          path: ~/.cache/grax
          key: datasets-${{ hashFiles('examples/*.py') }}
          restore-keys: datasets-

      - name: Run examples
        env:
          MPLBACKEND: Agg
        run: |
          for f in examples/*.py; do
            echo "::group::$f"
            uv run python "$f"
            echo "::endgroup::"
          done
