name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt
          pip install coveralls
          pip install -e .

      - name: Check types
        run: mypy ./grax

      - name: Run tests
        run: pytest

      - name: Upload coverage data to coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

