name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt
          pip install .

      - name: Check types
        run: mypy ./grax

      - name: Run tests
        run: |
          pytest
          coverage xml

      - name: Upload data to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.xml
