name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt
          pip install coveralls
          pip install -e .

      - name: Check types
        run: mypy ./grax ./tests

      - name: Run tests
        run: pytest ./tests

      - name: Upload coverage data to coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
